
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
  celery:
    depends_on:
      - redis
      - postgres
    command: sh -c "celery -A src.scrap.celery worker --loglevel=info -P solo & celery -A src.scrap.tasks beat --loglevel=info"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0

  dev:
    depends_on:
      - postgres
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"



volumes:
  postgres_data: